version: 2.1

jobs:
  build:
    docker:
      - image: node:16
    working_directory: ~/vleague/packages/web
    steps:
      - checkout
      - run:
          name: 'Installing Dependencies'
          command: yarn install
      - run:
          name: 'Build Production'
          command: yarn build
      - run:
          name: 'Check Files & Folder'
          command: pwd && ls -la
      - store_artifacts:
          path: ./.next
          destination: build
  test:
    docker:
      - image: node:16
    working_directory: ~/vleague/packages/web
    steps:
      - checkout
      - run:
          name: 'Installing Dependencies'
          command: yarn install
      - run:
          name: 'Unit Tests'
          command: yarn test
      - run:
          name: 'Check Files & Folder'
          command: pwd && ls -la
      - store_test_results:
          path: ./coverage

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
