version: 2.1

jobs:
  build:
    docker:
      - image: node:18
    working_directory: ~/vleague
    steps:
      - checkout
      - run:
          name: 'Installing Dependencies'
          command: yarn install
      - run:
          name: 'Build Production'
          command: yarn build
  test:
    docker:
      - image: node:18
    working_directory: ~/vleague
    steps:
      - checkout
      - run:
          name: 'Installing Dependencies'
          command: yarn install
      - run:
          name: 'Unit Tests'
          command: yarn test

workflows:
  version: 2
  build_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
